---
name: "Web Application"
root_url: "http://my-jenkins-host/"
folder: "MyFolderName"
id: web-application
jobs:
- name: Unit Test
  ci_name: MyFolderName-UnitTest
- name: Build
  ci_name: MyFolderName-Build
  upstream: MyFolderName-UnitTest
- name: Dev Deploy
  ci_name: MyFolderName-Dev-Deploy
  upstream: MyFolderName-Build
